# Generated by Django 5.0.7 on 2025-05-21 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('total_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pdf_oc', models.FileField(blank=True, null=True, upload_to='documentos_oc/')),
                ('pdf_nr', models.FileField(blank=True, null=True, upload_to='documentos_nr/')),
                ('apoyo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.apoyo')),
            ],
        ),
        migrations.CreateModel(
            name='AsistenciaEnOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.asistencia')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='gestion.ordenpago')),
            ],
        ),
    ]
