# Generated by Django 5.0.14 on 2025-05-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administradores',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_administrador', models.CharField(max_length=100)),
                ('apellido_adminstrador', models.CharField(max_length=100)),
                ('correo_adminstrador', models.CharField(max_length=100)),
                ('contraseña', models.CharField(max_length=100)),
                ('fcreacion_administrador', models.DateField(auto_now_add=True)),
                ('sede_administrador', models.CharField(max_length=100)),
            ],
        ),
    ]
