# Generated by Django 5.0.14 on 2025-05-22 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_administradores'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administradores',
            old_name='id',
            new_name='id_administrador',
        ),
    ]
