# Generated by Django 5.0.14 on 2025-05-22 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_rename_id_administradores_id_administrador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administradores',
            old_name='apellido_adminstrador',
            new_name='apellido_administrador',
        ),
        migrations.RenameField(
            model_name='administradores',
            old_name='contraseña',
            new_name='contraseña_administrador',
        ),
        migrations.RenameField(
            model_name='administradores',
            old_name='correo_adminstrador',
            new_name='correo_administrador',
        ),
    ]
