# Generated by Django 5.0.14 on 2025-05-23 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_rename_apellido_adminstrador_administradores_apellido_administrador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administradores',
            name='id_administrador',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
