# Generated by Django 5.0.14 on 2025-05-23 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0005_alter_administradores_id_administrador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_administrador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_administrador', models.CharField(max_length=100)),
                ('apellido_administrador', models.CharField(max_length=100)),
                ('correo_administrador', models.CharField(max_length=100)),
                ('contraseña_administrador', models.CharField(max_length=100)),
                ('fcreacion_administrador', models.DateField(auto_now_add=True)),
                ('sede_administrador', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='administradores',
            name='id_administrador',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
