# Generated by Django 5.0.14 on 2025-07-01 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0006_administrador_alter_administradores_id_administrador'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administradores',
        ),
    ]
