# Generated by Django 5.0.14 on 2025-07-01 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos_utp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotor',
            old_name='apellidos',
            new_name='apellidos_promotor',
        ),
        migrations.RenameField(
            model_name='promotor',
            old_name='codigo',
            new_name='codigo_promotor',
        ),
        migrations.RenameField(
            model_name='promotor',
            old_name='correo',
            new_name='correo_promotor',
        ),
        migrations.RenameField(
            model_name='promotor',
            old_name='dni',
            new_name='dni_promotor',
        ),
        migrations.RenameField(
            model_name='promotor',
            old_name='nombres',
            new_name='nombres_promotor',
        ),
        migrations.RenameField(
            model_name='promotor',
            old_name='telefono',
            new_name='telefono_promotor',
        ),
    ]
