# Generated by Django 5.0.14 on 2025-07-01 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos_utp', '0003_rename_correo_apoyo_correo_apoyo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotor',
            old_name='apellidos_promotor',
            new_name='nombre_completo_promotor',
        ),
        migrations.RemoveField(
            model_name='promotor',
            name='nombres_promotor',
        ),
    ]
