# Generated by Django 5.0.14 on 2025-07-02 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos_utp', '0004_rename_apellidos_promotor_promotor_nombre_completo_promotor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colegio',
            old_name='apellidos_encargado_colegio',
            new_name='nombres_completo_encargado_colegio',
        ),
        migrations.RemoveField(
            model_name='colegio',
            name='nombres_encargado_colegio',
        ),
    ]
