# Generated by Django 5.0.14 on 2025-07-02 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos_utp', '0005_rename_apellidos_encargado_colegio_colegio_nombres_completo_encargado_colegio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colegio',
            old_name='nombres_completo_encargado_colegio',
            new_name='nombre_completo_encargado_colegio',
        ),
    ]
