# Generated by Django 5.0.14 on 2025-07-06 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos_utp', '0006_rename_nombres_completo_encargado_colegio_colegio_nombre_completo_encargado_colegio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colegio',
            name='archivo_excel_colegio',
        ),
    ]
