# Generated by Django 5.0.14 on 2025-07-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos_utp', '0007_remove_colegio_archivo_excel_colegio'),
    ]

    operations = [
        migrations.AddField(
            model_name='colegio',
            name='archivo_excel_colegio',
            field=models.BinaryField(blank=True, max_length='max', null=True),
        ),
    ]
