# Generated by Django 5.0.14 on 2025-07-06 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos_utp', '0008_colegio_archivo_excel_colegio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AsistenciaEnOrden',
        ),
    ]
