# Generated by Django 5.0.14 on 2025-07-06 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos_utp', '0009_delete_asistenciaenorden'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asistencia',
            old_name='apoyo',
            new_name='apoyo_asistencia',
        ),
        migrations.RenameField(
            model_name='asistencia',
            old_name='colegio',
            new_name='colegio_asistencia',
        ),
        migrations.RenameField(
            model_name='asistencia',
            old_name='fecha',
            new_name='fecha_asistencia',
        ),
        migrations.RenameField(
            model_name='asistencia',
            old_name='rol',
            new_name='rol_asistencia',
        ),
        migrations.RenameField(
            model_name='asistencia',
            old_name='turno',
            new_name='turno_asistencia',
        ),
    ]
