# Generated by Django 5.0.14 on 2025-07-06 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos_utp', '0010_rename_apoyo_asistencia_apoyo_asistencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='rol_asistencia',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='turno_asistencia',
        ),
    ]
