# Generated by Django 5.0.14 on 2025-07-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos_utp', '0011_remove_asistencia_rol_asistencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='rol_asistencia',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asistencia',
            name='turno_asistencia',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
