# Generated by Django 5.0.14 on 2025-07-06 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos_utp', '0012_asistencia_rol_asistencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='asistencia_asistencia',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='rol_asistencia',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='turno_asistencia',
            field=models.CharField(max_length=50),
        ),
    ]
