# Generated by Django 5.0.14 on 2025-07-08 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos_utp', '0013_asistencia_asistencia_asistencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='monto_pagado_asistencia',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
