# Generated by Django 5.0.7 on 2025-07-09 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos_utp', '0014_asistencia_monto_pagado_asistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='orden_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_incluidas', to='Eventos_utp.ordenpago'),
        ),
    ]
